jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw -B package verify
    strategy:
      matrix:
        java_version:
        - 11
        - 12
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
